// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	coupon "kupon/features/coupon"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddCoupon provides a mock function with given fields: token, newCoupon
func (_m *Service) AddCoupon(token *jwt.Token, newCoupon coupon.Coupon) (coupon.Coupon, error) {
	ret := _m.Called(token, newCoupon)

	var r0 coupon.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, coupon.Coupon) (coupon.Coupon, error)); ok {
		return rf(token, newCoupon)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, coupon.Coupon) coupon.Coupon); ok {
		r0 = rf(token, newCoupon)
	} else {
		r0 = ret.Get(0).(coupon.Coupon)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, coupon.Coupon) error); ok {
		r1 = rf(token, newCoupon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoupons provides a mock function with given fields: token
func (_m *Service) GetCoupons(token *jwt.Token) ([]coupon.Coupon, error) {
	ret := _m.Called(token)

	var r0 []coupon.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token) ([]coupon.Coupon, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token) []coupon.Coupon); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coupon.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
