// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	users "kupon/features/users"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetUser provides a mock function with given fields:
func (_m *Service) GetUser() ([]users.User, error) {
	ret := _m.Called()

	var r0 []users.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]users.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []users.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]users.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password
func (_m *Service) Login(email string, password string) (users.User, error) {
	ret := _m.Called(email, password)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (users.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) users.User); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: newUser
func (_m *Service) Register(newUser users.User) (users.User, error) {
	ret := _m.Called(newUser)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(users.User) (users.User, error)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(users.User) users.User); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(users.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: token, updateUser
func (_m *Service) Update(token *jwt.Token, updateUser users.User) (users.User, error) {
	ret := _m.Called(token, updateUser)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Token, users.User) (users.User, error)); ok {
		return rf(token, updateUser)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Token, users.User) users.User); ok {
		r0 = rf(token, updateUser)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Token, users.User) error); ok {
		r1 = rf(token, updateUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
